apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <YOUR_BACKEND_IMAGE>
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8000
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
